# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: ffcb0ae
_src_path: https://github.com/SS-NES/notebook-template
citation: false
code_of_conduct: true
community: false
contact_email: contact@gmail.com
copyright_holder: John Doe
documentation: true
documentation_type: user
owner: John Doe
project_name: Fibonacci Sequence
project_purpose: To show fibonacci sequence
software_license: MIT License
