# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 6ba476c
_src_path: notebook-template
citation: false
code_of_conduct: false
community: false
copyright_holder: Iowner
documentation: false
owner: Iowner
project_name: awesome-project
project_purpose: The purpose of Awesome is ...
software_license: MIT License
